'use client';

import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from 'sonner';
import { TextField, TextAreaField } from '@/components/ui/form-fields';
import type { BookingSettingsFormValues } from '@/lib/validations/settings';
import { saveBookingSettings } from './actions';

export function BookingSettingsForm({
  initialValues,
}: {
  initialValues: Partial<BookingSettingsFormValues>;
}) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [values, setValues] = useState<Partial<BookingSettingsFormValues>>({
    booking_prefix: 'BK',
    currency: 'INR',
    default_tax_percent: 0,
    ...initialValues,
  });

  function set<K extends keyof BookingSettingsFormValues>(key: K, value: BookingSettingsFormValues[K]) {
    setValues((v) => ({ ...v, [key]: value }));
  }

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    startTransition(async () => {
      const result = await saveBookingSettings(values);
      if (result.error) {
        toast.error(result.error);
        return;
      }
      toast.success('Settings saved');
      router.refresh();
    });
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <p className="rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-800">
        Note: booking numbers are currently auto-generated by the database as BK-YYYY-NNNNN (see
        migration 004). Changing the prefix here is stored for reference and future use, but
        won&apos;t retroactively change the DB sequence format without a migration update.
      </p>
      <div className="grid gap-4 sm:grid-cols-3">
        <TextField
          label="Booking number prefix"
          value={values.booking_prefix ?? 'BK'}
          onChange={(e) => set('booking_prefix', e.target.value)}
        />
        <TextField
          label="Default currency"
          value={values.currency ?? 'INR'}
          onChange={(e) => set('currency', e.target.value.toUpperCase())}
        />
        <TextField
          label="Default tax %"
          type="number"
          min={0}
          max={100}
          value={values.default_tax_percent ?? 0}
          onChange={(e) => set('default_tax_percent', Number(e.target.value))}
        />
      </div>
      <TextAreaField
        label="Default booking terms"
        rows={4}
        value={values.booking_terms ?? ''}
        onChange={(e) => set('booking_terms', e.target.value)}
      />
      <div className="flex justify-end">
        <button type="submit" disabled={isPending} className="btn-primary">
          {isPending ? 'Saving…' : 'Save booking settings'}
        </button>
      </div>
    </form>
  );
}
